name: Gold Data Collector

on:
  schedule:
    - cron: '0 * * * *'  # هر ۶۰ دقیقه یکبار اجرا می‌شود
  workflow_dispatch:      # امکان اجرای دستی

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r reqs.txt

      - name: Run collector
        run: python collector.py

      - name: Commit and push CSV changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add gold_data.csv
          git diff --staged --quiet || git commit -m "Update gold data"
          git push
