name: Test Bonbast
on: [workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run test
        run: |
          pip install requests beautifulsoup4
          python check_bonbast.py
